# Generated by Django 5.1.4 on 2024-12-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='formacao_academica',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
