# Generated by Django 5.1.4 on 2024-12-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_professor_formacao_academica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('AULA_EXTRA', 'Aula Extra'), ('REUNIAO', 'Reunião'), ('WORKSHOP', 'Workshop'), ('PALESTRA', 'Palestra'), ('OUTRO', 'Outro')], max_length=20)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('local', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.professor')),
                ('turmas', models.ManyToManyField(blank=True, related_name='eventos', to='core.turma')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
    ]
