# Generated by Django 5.1.4 on 2024-12-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_evento_data_alter_evento_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('palestrante', models.CharField(max_length=100, verbose_name='Palestrante')),
                ('email_palestrante', models.EmailField(blank=True, max_length=254, verbose_name='E-mail do Palestrante')),
                ('telefone_palestrante', models.CharField(blank=True, max_length=15, verbose_name='Telefone do Palestrante')),
                ('categoria', models.CharField(choices=[('TECNOLOGIA', 'Tecnologia'), ('EDUCACAO', 'Educação'), ('SAUDE', 'Saúde'), ('CARREIRA', 'Carreira'), ('MOTIVACIONAL', 'Motivacional'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de Término')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('capacidade', models.PositiveIntegerField(verbose_name='Capacidade de Participantes')),
                ('publico_alvo', models.TextField(verbose_name='Público Alvo')),
                ('requisitos', models.TextField(blank=True, help_text='Requisitos ou materiais necessários para participar', verbose_name='Requisitos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palestras', to='core.professor', verbose_name='Professor Responsável')),
                ('turmas_convidadas', models.ManyToManyField(blank=True, related_name='palestras', to='core.turma', verbose_name='Turmas Convidadas')),
            ],
            options={
                'verbose_name': 'Palestra',
                'verbose_name_plural': 'Palestras',
                'ordering': ['data', 'hora_inicio'],
                'unique_together': {('data', 'hora_inicio', 'local')},
            },
        ),
    ]
